// Auto-generated by scripts/generateRegistry.ts — do not edit manually
import { ComponentType } from 'react'
import PaiGow from '@/components/games/pai-gow/PaiGowGame'
import ExampleGame from '@/components/games/example-game/ExampleGame'
import FoxyShooter from '@/components/games/foxy-shooter/FoxyShooter'
import StreetLooker from '@/components/games/street-looker/StreetLooker'
import ChickenCrossing from '@/components/games/chicken-crossing/ChickenCrossing'
import LootTumble from '@/components/games/loot-tumble/LootTumble'

const gameRegistry: Record<string, ComponentType> = {
  'pai-gow': PaiGow,
  'example-game': ExampleGame,
  'foxy-shooter': FoxyShooter,
  'street-looker': StreetLooker,
  'chicken-crossing': ChickenCrossing,
  'loot-tumble': LootTumble,
}

export { gameRegistry }
